components:
    schemas:
        Match:
            type: object
            properties:
                matchid: 
                  type: string
                userid_1: 
                  type: string
                qualification_1: 
                  type: string
                userid_2:
                  type: string
                qualification_2:
                  type: string
            required:
                - matchid
                - userid_1
                - qualification_1
                - userid_2
                - qualification_2

