paths:
  /api/user/profile:
    post:
        summary: user creates profile.
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
        requestBody:
            required: true
            content: 
                application/json:
                    schema:
                        type: object
                        $ref: '#/components/schemas/Profile'
        responses:
            200: 
                description: return profile!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "info about requireds fields".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"
  /api/user/profile/{id}:
    get:
        summary: user or admin get a profile with pictures.
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        responses:
            200: 
                description: return profile!
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ProfilePictures'
            422:
                description: return error "info about requireds fields".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"
    put:
        summary: user updates profile
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        requestBody:
            required: true
            content: 
                application/json:
                    schema:
                        type: object
                        $ref: '#/components/schemas/Profile'
        responses:
            200: 
                description: return profile updated!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "validation error".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"
    delete:
        summary: user or admin deletes profile
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        responses:
            200: 
                description: return profile updated!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "validation error".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"
  /api/user/profile/pictures:
    post:
        summary: user creates pictures
        tags: [Picture]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
        requestBody:
            required: true
            content: 
                application/json:
                    schema:
                        type: object
                        $ref: '#/components/schemas/Pictures'
        responses:
            200: 
                description: return successful response!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "info about requireds fields".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"
  /api/user/profile/pictures/{id}:
    get:
        summary: user of admin view user pictures
        tags: [Picture]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        responses:
            200: 
                description: returns pictures list!
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/Pictures'
            422:
                description: return error "info about requireds fields".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/HTTPValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"
    put:
        summary: user update pictures 
        tags: [Picture]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        requestBody:
            required: true
            content: 
                application/json:
                    schema:
                        type: object
                        $ref: '#/components/schemas/Pictures'
        responses:
            200: 
                description: return successful response!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "info about requireds fields".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/HTTPValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"
  /api/users/profiles:
    get:
        summary: user or admin get profiles list 
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
        responses:
            200:
                description: returns profiles list!
                content:
                    application/json:
                        schema:
                            type: array
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
            503:
                description: service not available!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: "Service not available"