paths:
  /api/profiles/user/profile:
    post:
        summary: creates profile (aún no es funcional token, se puede poner cualquier cosa)
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
        requestBody:
            required: true
            content: 
                application/json:
                    schema:
                        type: object
                        $ref: '#/components/schemas/Profile'
        responses:
            200: 
                description: return profile!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "info about requireds fields".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
  /api/profiles/user/profile/{id}:
    get:
        summary: get profile (aún no es funcional token, se puede poner cualquier cosa)
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        responses:
            200: 
                description: return profile!
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/Profile'
            422:
                description: return error "info about requireds fields".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
    put:
        summary: updates profile (aún no es funcional token, se puede poner cualquier cosa)
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        requestBody:
            required: true
            content: 
                application/json:
                    schema:
                        type: object
                        $ref: '#/components/schemas/Profile'
        responses:
            200: 
                description: return profile updated!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "validation error".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
    delete:
        summary: deletes profile (aún no es funcional token, se puede poner cualquier cosa)
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
            - in: path
              name: id
              required: true
              schema:
                type: string
        responses:
            200: 
                description: return profile updated!
                content:
                    application/json:
                        schema:
                            type: string
            422:
                description: return error "validation error".
                content:
                    application/json:
                        schema:
                            type: object
                            $ref: '#/components/schemas/ValidationError'
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
/api/profiles/users/profiles:
    get:
        summary: returns profiles list (aún no es funcional token, se puede poner cualquier cosa)
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
        responses:
            200: 
                description: returns profiles list!
                content:
                    application/json:
                        schema:
                            type: array
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator
/api/profiles/status:
    get:
        summary: returns service status (aún no es funcional token, se puede poner cualquier cosa)
        tags: [Profile]
        parameters:
            - in: header
              name: x-token
              schema:
                type: string
                required: true
                description: user token
        responses:
            200: 
                description: returns profiles list!
                content:
                    application/json:
                        schema:
                            type: object
            500:
                description: return internal error!
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                ok:
                                    type: boolean
                                    example: false
                                msg:
                                    type: string
                                    example: Please talk to the administrator