components:
    schemas:
      Profile:
        type: object
        properties:
          userid: 
            type: string
            description: unique user id
          username:
            type: string
          email:
            type: string
          description:
            type: string
          gender:
            type: string
            enum: [Hombre, Mujer]
          looking_for:
            type: string
            enum: [Hombre, Mujer]
          age:
            type: integer
          education:
            type: string
          ethnicity:
            type: string
        example:
          userid: '66304a6b2891cdcfebdbdc6c'
          username: Carlos Carlin
          email: carlin@mail.com
          description: Argentino. Estudié en la UBA.
          gender: Hombre
          looking_for: Mujer
          age: 33
          education: Ingeniero Civil
          ethnicity: europeo
      HTTPValidationError:
        type: object
        properties:
          detail:
            type: object
      ValidationError:
        type: object
        properties:
          loc:
            type: object
          msg:
            type: string
          type:
            type: string
      Picture:
        type: object
        properties:
          name: 
            type: string
          url: 
            type: string
          order: 
            type: integer
      Pictures:
        type: object
        properties:
          userid: 
            type: string
          pictures: 
            type: array
            items:
              type: object
              $ref: '#/components/schemas/Picture'
      ProfilePictures:
        type: object
        properties:
          userid: 
            type: string
            description: unique user id
          username:
            type: string
          email:
            type: string
          description:
            type: string
          gender:
            type: string
            enum: [Hombre, Mujer]
          looking_for:
            type: string
            enum: [Hombre, Mujer]
          age:
            type: integer
          education:
            type: string
          ethnicity:
            type: string
          pictures:
            type: array
            items: 
              type: object
              $ref: '#/components/schemas/Picture'
