components:
    schemas:
        User:
            type: object
            properties:
                email:
                    type: string
                    description: unique user email
                password:
                    type: string
                    description: user password. Numbers, letters and at least one symbol
                    minLength: 6
                role:
                    type: string
                    description: role in the system
                    enum: [administrador, cliente]
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
                verified:
                    type: boolean
                    description: unique. User has ben verified.
            required: 
                - email
                - password
                - role
                - verified
            example:
                email: carlos@mail.com
                password: cli123te1*
                role: cliente
                blocked: false
                verified: true
        UserCreateData:
            type: object
            properties:
                email:
                    type: string
                    description: unique user email
                password:
                    type: string
                    description: user password. Numbers, letters and at least one symbol
                    minLength: 6
                role:
                    type: string
                    description: role in the system
                    enum: [administrador, cliente]
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
            required: 
                - email
                - password
                - role
            example:
                email: carlos@mail.com
                password: cli123te1*
                role: cliente
                blocked: false
        UserSharedData:
            type: object
            properties:
                uid:
                    type: string
                    description: unique user id 
                email:
                    type: string
                    description: unique user email              
                role:
                    type: string
                    description: cliente or administrador
                    enum: [administrador, cliente]
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
                verified:
                    type: boolean
                    description: unique. User has ben verified.
            required: 
                - email
                - password
                - role
                - blocked
                - verified
            example:
                id: 645547541243dfdsfe2132142134234203
                email: rafaelputaro@gmail.com
                role: administrador
                blocked: false
                verified: true
        UserUpdateData:
            type: object
            properties:
                email:
                    type: string
                    description: unique user email              
                password:
                    type: string
                    description: user password. Numbers, letters and at least one symbol
                    minLength: 6
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.
            example:
                email: carlos@mail.com
                password: cli123te1*
                blocked: false
        ServicesStatus:
            type: object
            properties:
                services:
                    type: object
                    properties:
                        matches: 
                            type: object
                            $ref: '#/components/schemas/ServiceStatus'
                        messages:
                            type: object
                            $ref: '#/components/schemas/ServiceStatus'
                        profiles:
                            type: object
                            $ref: '#/components/schemas/ServiceStatus'
                        users:
                            type: object
                            $ref: '#/components/schemas/ServiceStatus'
        ServiceStatus:
            type: object
            properties:
                active: 
                    type: boolean
                target:
                    type: string
                online: 
                    type: boolean
                detail:
                    type: object        
        TokenPayload:
            type: object
            properties:
                uid:
                    type: string
                    description: unique user id 
                role:
                    type: string
                    description: cliente or administrador
                    enum: [administrador, cliente]
                blocked:
                    type: boolean
                    description: unique. Disables the service for the user.