components:
    schemas:
        ViewMatchs:
            type: object
            properties:
                matches:
                  type: array
                  items:
                    type: object

